name: deploy

on:
  push:
    branches:
      - main
  schedule:
    # 4/5 means: start on the 4th minute after hour,
    # as github mentions congestion at the top of the hour
    # then run the job every 5 minutes after that
    - cron: '4/5 * * * *'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # - name: Cancel other deploys which are running
      #   uses: styfle/cancel-workflow-action@0.9.0
      #   with:
      #     access_token: ${{ github.token }}

       - run: yarn install --frozen-lockfile

      - env:
          GITHUB_ORGS_ALL_REPOS: >-
            compository
            eyss
            h-be
            hc-institute-japan
            holo-host
            holochain
            holochain-ci
            holochain-gym
            holochain-in-action
            holochain-open-dev
            juntofoundation
          # possible additions include:
          # glassbeadsoftware
          # perspect3vism
          # Sprillow
          MAX_DAYS_SINCE_LAST_PUSH: 180
          MAX_REPOS: 1000
          PUBLIC_REPOS_GITHUB_ACCESS_TOKEN: ${{ secrets.PUBLIC_REPOS_GITHUB_ACCESS_TOKEN }}
          UPDATE_EXISTING_REPOS: true
        run: yarn build

      - name: Deploy with gh-pages
        run: |
          set -x
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          yarn deploy --user "Deploy Bot <noreply@example.com>" --message "Update from Github Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,ref,workflow,job
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL_CI }}
        if: failure()
